apiVersion: v1
kind: Service
metadata:
  name: redis-cache-example
  labels:
    app: redis
spec:
  selector:
    app: redis-cache-example
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379